version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "restapi-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d4b27wo41ze5"
s3_prefix = "restapi-example"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"DEV\""
image_repositories = []
